### ISSUE TITLE
Download model hash error

### ISSUE THREAD

**Issue by dmitry-rvn** [stanfordnlp/stanza-resources#10]
Today with stanza 1.4.1 and 1.4.2 command `stanza.download('ru')` stopped working because of invalid hash:

```
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.4.1.json: 193kB [00:00, 19.4MB/s]                    
2022-10-13 11:23:56 INFO: Downloading default packages for language: ru (Russian) ...
Downloading https://huggingface.co/stanfordnlp/stanza-ru/resolve/v1.4.1/models/default.zip: 100%|██████████| 320M/320M [00:28<00:00, 11.2MB/s]
Traceback (most recent call last):
  File "C:\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\dshol\PycharmProjects\stanza-test\venv\lib\site-packages\stanza\resources\common.py", line 562, in download
    request_file(
  File "C:\Users\dshol\PycharmProjects\stanza-test\venv\lib\site-packages\stanza\resources\common.py", line 154, in request_file
    assert_file_exists(path, md5, alternate_md5)
  File "C:\Users\dshol\PycharmProjects\stanza-test\venv\lib\site-packages\stanza\resources\common.py", line 107, in assert_file_exists
    raise ValueError("md5 for %s is %s, expected %s" % (path, file_md5, md5))
ValueError: md5 for C:\Users\dshol\stanza_resources\ru\default.zip is 74d2e7c2f2f2c42546fe8fd4791287a9, expected 0b9c256b95802c79eb028589667fa88b
```

Couple of days ago everything was OK.

**Comment by dmitry-rvn** [comment]
Apparently there was a time gap between updating json (hashes) and zip (model) files. Now it's OK.

```
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.4.1.json: 193kB [00:00, 12.6MB/s]                    
2022-10-13 12:27:21 INFO: Downloading default packages for language: ru (Russian) ...
Downloading https://huggingface.co/stanfordnlp/stanza-ru/resolve/v1.4.1/models/default.zip: 100%|██████████| 597M/597M [00:53<00:00, 11.2MB/s]
2022-10-13 12:28:21 INFO: Finished downloading models and saved to C:\Users\dshol\stanza_resources.
```

**Comment by AngledLuffa** [comment]
Yes, that's it exactly.  I updated `default.zip` to include the embeddings used by the NER model, and it took a little time to upload.  Sorry for the inconvenience

**Comment by godlockin** [comment]
this issue happens again..
i tried the code
```python
import stanza
stanza.download('en')

nlp = stanza.Pipeline(lang='en', processors='tokenize,ner')
```

and got the error:
```
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.2.2.json:
140k/? [00:00<00:00, 7.39MB/s]
2024-05-13 17:28:59 INFO: Downloading default packages for language: en (English)...
Downloading http://nlp.stanford.edu/software/stanza/1.2.2/en/default.zip: 100%
559/559 [00:00<00:00, 142kB/s]
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_1385137/1987586062.py in <module>
      1 import stanza
----> 2 stanza.download('en')
      3 
      4 nlp = stanza.Pipeline(lang='en', processors='tokenize,ner')

/opt/miniconda3/envs/standford_nlp/lib/python3.7/site-packages/stanza/resources/common.py in download(lang, model_dir, package, processors, logging_level, verbose, resources_url, resources_branch, resources_version, model_url, proxies)
    429             os.path.join(model_dir, lang, f'default.zip'),
    430             proxies,
--> 431             md5=resources[lang]['default_md5'],
    432         )
    433         unzip(os.path.join(model_dir, lang), 'default.zip')

/opt/miniconda3/envs/standford_nlp/lib/python3.7/site-packages/stanza/resources/common.py in request_file(url, path, proxies, md5, raise_for_status)
    141         return
    142     download_file(url, path, proxies, raise_for_status)
--> 143     assert_file_exists(path, md5)
    144 
    145 def sort_processors(processor_list):

/opt/miniconda3/envs/standford_nlp/lib/python3.7/site-packages/stanza/resources/common.py in assert_file_exists(path, md5)
    108     if md5:
    109         file_md5 = get_md5(path)
--> 110         assert file_md5 == md5, "md5 for %s is %s, expected %s" % (path, file_md5, md5)
    111 
    112 def download_file(url, path, proxies, raise_for_status=False):

AssertionError: md5 for /home/algo/stanza_resources/en/default.zip is eefae146c4eda222ef551bb083d9d3c2, expected 5a2f0714cc56a4d50f4707d2c8ac70b3
```

**Comment by AngledLuffa** [comment]
I'm not sure how I'm supposed to help when there's zero information
provided about version or environment

The latest version successfully runs `download('en')` for me.

OTOH, the latest versions no longer support Python 3.7, since it is past
its end of life.

https://devguide.python.org/versions/
